name: Create Release

on:
  push:
    branches:
      - flexy

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from composer.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' composer.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.version }} --generate-notes --latest
